### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by JFreegman** [elastos/Elastos.NET.Carrier.Crawler#10]
Your removal of the [original copyright holder ](https://github.com/JFreegman/toxcrawler/blob/master/crawler/src/main.c#L4)for this software is a violation of the GPLV3 licence. You can read more about how to properly use source code derived from software licensed under GPLV3 [here](https://www.gnu.org/licenses/gpl-howto.en.html), specifically the `The copyright notice` section.

**Comment by jingyu** [comment]
@JFreegman  Sorry for removed the original copyright holder. We added the original license header in the main.c.

**Comment by JFreegman** [comment]
Not a problem, I see that you re-added it. Thanks!
